#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt', '~> 2.6.0'

cookbook 'build-essential', '~> 2.0.6'

cookbook 'chef-client', '~> 3.8.0'

cookbook 'elasticsearch', '~> 0.3.10'

cookbook 'java', '~> 1.28.0'

cookbook 'git', '~> 4.0.2'

cookbook 'nodejs', '~> 2.2.0'

cookbook 'rvm', '~> 0.9.2'

cookbook 'python', '~> 1.4.6'